version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1341:5000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    build: services/postgres
    volumes:
      - ./:/tmp/db
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 12346:5432

  frontend:
    build: ./services/frontend  # Assuming this is where the React app's Dockerfile is located
    ports:
      - "3000:3000"  # React app will run on port 3000
    volumes:
      - ./services/frontend:/app  # Mounting the local directory into the container
    stdin_open: true  # Keeps the container open for interactive commands
    tty: true         # Allocates a pseudo-TTY for interactive commands
    depends_on:
      - web
      - postgres

volumes:
  postgres_data:
